version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-afiliacion
    environment:
      POSTGRES_DB: afiliacion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  app:
    build: .
    container_name: afiliacion_app
    depends_on:
      - postgres
    ports:
      - "8082:8082"